<a href="https://colab.research.google.com/github/Dhruvjain484/Machine-learning-projects-for-beginner/blob/main/50%20Startups/50_Startups.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Importing the libraries

In [59]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

##Importing the dataset

In [60]:
dataset = pd.read_csv('50_Startups.csv')

dataset.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [61]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [75]:
dataset.corr() #Determining the correlation between different features

R&D Spend  Administration  Marketing Spend    Profit
R&D Spend         1.000000        0.241955         0.724248  0.972900
Administration    0.241955        1.000000        -0.032154  0.200717
Marketing Spend   0.724248       -0.032154         1.000000  0.747766
Profit            0.972900        0.200717         0.747766  1.000000

In [62]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [63]:
y = y.reshape(len(y), 1)

##Encoding Categorical Data

In [64]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])] , remainder= 'passthrough')
x = ct.fit_transform(x)
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

##Scaling the dataset


In [65]:
from sklearn.preprocessing import StandardScaler
scaled_x = StandardScaler()
scaled_y = StandardScaler()

x[:, 3:] = scaled_x.fit_transform(x[:, 3:])
y = scaled_y.fit_transform(y)


##Training the Regression model on the dataset

In [66]:
from sklearn.linear_model import LinearRegression 
regressor = LinearRegression()

# from sklearn.svm import SVR
# regressor = SVR(kernel= 'rbf')

# from sklearn.ensemble import RandomForestRegressor
# regressor = RandomForestRegressor()

# from xgboost import XGBRegressor
# regressor = XGBRegressor()
regressor.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

##Predicting the result

In [67]:
y_pred = scaled_y.inverse_transform(regressor.predict(x))
np.set_printoptions(precision = 2) #Number of digits to appear after decimal point
y_pred = y_pred.reshape(len(y_pred), 1)
y_pred

array([[192390.57],
       [189071.32],
       [182276.19],
       [173584.98],
       [172277.13],
       [163473.81],
       [158099.29],
       [160155.64],
       [151634.74],
       [154829.66],
       [135664.64],
       [135528.6 ],
       [129282.92],
       [127431.25],
       [149694.38],
       [146143.64],
       [116854.07],
       [130085.41],
       [129149.73],
       [115594.19],
       [116570.73],
       [117201.51],
       [114833.31],
       [110123.8 ],
       [113294.37],
       [102200.27],
       [110765.3 ],
       [114279.8 ],
       [101818.59],
       [101721.04],
       [ 99629.01],
       [ 97617.3 ],
       [ 98988.24],
       [ 98061.36],
       [ 88974.7 ],
       [ 90420.01],
       [ 75423.09],
       [ 89577.7 ],
       [ 69606.52],
       [ 83684.98],
       [ 74762.75],
       [ 74956.31],
       [ 70575.99],
       [ 60100.27],
       [ 64585.15],
       [ 47588.36],
       [ 56272.99],
       [ 46468.23],
       [ 49123.07],
       [ 48185.04]])

In [71]:
np.concatenate((scaled_y.inverse_transform(y), y_pred), 1)

array([[192261.83, 192390.57],
       [191792.06, 189071.32],
       [191050.39, 182276.19],
       [182901.99, 173584.98],
       [166187.94, 172277.13],
       [156991.12, 163473.81],
       [156122.51, 158099.29],
       [155752.6 , 160155.64],
       [152211.77, 151634.74],
       [149759.96, 154829.66],
       [146121.95, 135664.64],
       [144259.4 , 135528.6 ],
       [141585.52, 129282.92],
       [134307.35, 127431.25],
       [132602.65, 149694.38],
       [129917.04, 146143.64],
       [126992.93, 116854.07],
       [125370.37, 130085.41],
       [124266.9 , 129149.73],
       [122776.86, 115594.19],
       [118474.03, 116570.73],
       [111313.02, 117201.51],
       [110352.25, 114833.31],
       [108733.99, 110123.8 ],
       [108552.04, 113294.37],
       [107404.34, 102200.27],
       [105733.54, 110765.3 ],
       [105008.31, 114279.8 ],
       [103282.38, 101818.59],
       [101004.64, 101721.04],
       [ 99937.59,  99629.01],
       [ 97483.56,  97617.3 ],
       [

##Checking the accuracy

In [74]:
from sklearn.metrics import r2_score
r2_score(scaled_y.inverse_transform(y) ,y_pred)

0.9507524843355148